version: 2.1

jobs:
  deploy:
    docker:
      - image: google/cloud-sdk
    steps:
      - checkout
      - run:
          name: GCP OIDC auth
          command: |
            GCP_OIDC_PROVIDER_ID="circleci"
            GCP_PROJECT_ID="${GCP_PROJECT_ID}"
            GCP_SERVICE_ACCOUNT_EMAIL="circleci-oidc@${GCP_PROJECT_ID}.iam.gserviceaccount.com"
            GCP_WORKLOAD_IDENTITY_POOL_ID="circleci-oidc"
            GCP_OIDC_AUDIENCE="projects/${GCP_PROJECT_ID}/locations/global/workloadIdentityPools/${GCP_WORKLOAD_IDENTITY_POOL_ID}/providers/${GCP_OIDC_PROVIDER_ID}"
            GCP_IMPERSONATION_URL="https://iamcredentials.googleapis.com/v1/projects/-/serviceAccounts/${GCP_SERVICE_ACCOUNT_EMAIL}:generateAccessToken"

            mkdir -p ~/.config/gcloud
            echo "${CIRCLE_OIDC_TOKEN}" > $HOME/.config/gcloud/oidc_access_token

            # Use \<< to escape the heredoc in YAML
            cat \<<EOF > $HOME/.config/gcloud/application_default_credentials.json
            {
              "type": "external_account",
              "audience": "//iam.googleapis.com/${GCP_OIDC_AUDIENCE}",
              "subject_token_type": "urn:ietf:params:oauth:token-type:jwt",
              "token_url": "https://sts.googleapis.com/v1/token",
              "credential_source": {
                "file": "$HOME/.config/gcloud/oidc_access_token"
              },
              "service_account_impersonation_url": "${GCP_IMPERSONATION_URL}"
            }
            EOF

            gcloud auth application-default print-access-token
            gcloud projects describe ${GCP_PROJECT_ID}

workflows:
  deploy-workflow:
    jobs:
      - deploy
