version: 2.1

executors:
  default:
    docker:
      - image: cimg/base:stable

jobs:
  deploy:
    executor: default
    steps:
      - checkout

      - run:
          name: Install gcloud SDK
          command: |
            sudo apt-get update
            sudo apt-get install -y apt-transport-https ca-certificates gnupg
            echo "deb [signed-by=/usr/share/keyrings/cloud.google.gpg] https://packages.cloud.google.com/apt cloud-sdk main" | \
              sudo tee -a /etc/apt/sources.list.d/google-cloud-sdk.list
            curl https://packages.cloud.google.com/apt/doc/apt-key.gpg | \
              sudo apt-key --keyring /usr/share/keyrings/cloud.google.gpg add -
            sudo apt-get update && sudo apt-get install -y google-cloud-sdk

      - run:
          name: Authenticate to Google Cloud using Workload Identity Federation (OIDC)
          command: |
            gcloud config set project sylvan-hydra-464904-d9

            gcloud iam workload-identity-pools create-cred-config \
              "projects/57920515119/locations/global/workloadIdentityPools/circleci-identity-pool/providers/circleci-oidc" \
              --service-account="circleci-deploy-sa@sylvan-hydra-464904-d9.iam.gserviceaccount.com" \
              --output-file="gcloud-credentials.json"

            gcloud auth login --cred-file="gcloud-credentials.json"

      - run:
          name: Example GCP Command - List Buckets
          command: |
            gcloud storage buckets list

workflows:
  version: 2
  deploy:
    jobs:
      - deploy
